### PR TITLE
feat: Misc. (#9)

### PR DESCRIPTION
**Pull request by FalloutCascadia**
* feat: BSRandom.

* feat: Inline function as it should be.

* feat: More misc. RE'ing.

* feat: AimModel RE.

* feat: Update IDs.

* feat: Missing import

### CODE REVIEW

**Comment by qudix** [comment]
I'm confused as to how it's compiling, but that `BSRandom` function isn't calling `func`

**Comment by FalloutCascadia** [comment]
And now with `func` in place, it fails to build?

**Comment by qudix** [comment]
Remove the extra closing bracket

**Comment by FalloutCascadia** [comment]
Good catch! Should all be good to go.

**Pull request merged**
